"""empty message

Revision ID: b97b93fb6665
Revises: 124a8d5f7051
Create Date: 2021-11-20 14:23:57.142808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b97b93fb6665'
down_revision = '124a8d5f7051'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('photo', sa.Unicode(length=128), nullable=True))
    op.add_column('User', sa.Column('forbidden_words', sa.Unicode(length=1024), nullable=True))
    op.add_column('User', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    op.add_column('User', sa.Column('deleted', sa.Boolean(), nullable=True))
    op.drop_column('User', 'is_admin')
    op.drop_column('User', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('phone', sa.VARCHAR(length=128), nullable=False))
    op.add_column('User', sa.Column('is_admin', sa.BOOLEAN(), nullable=True))
    op.drop_column('User', 'deleted')
    op.drop_column('User', 'is_blocked')
    op.drop_column('User', 'forbidden_words')
    op.drop_column('User', 'photo')
    # ### end Alembic commands ###
